services:
  - type: web
    name: vidsrc-extractor
    env: node
    plan: free
    repo: https://github.com/phisher98/vidsrc_wasm
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
